In [2]:
import pandas as pd
import os

# 1. Customer Master

In [3]:
df_master = pd.read_csv("../data/raw/customer_master.csv")

In [4]:
df_master

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

In [5]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  str
 1   customer_name              25000 non-null  str
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  str
 4   customer_segment           25000 non-null  str
 5   customer_city              25000 non-null  str
 6   customer_state             25000 non-null  str
 7   customer_country           25000 non-null  str
 8   region                     25000 non-null  str
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 MB

In [6]:
df_master.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [7]:
print(df_master.isnull().sum())

customer_id                  0
customer_name                0
customer_age                 0
gender                       0
customer_segment             0
customer_city                0
customer_state               0
customer_country             0
region                       0
customer_postal_code         0
customer_acquisition_cost    0
dtype: int64

In [8]:
print(f"Duplicated IDS : {df_master.duplicated(subset=['customer_id']).sum()}")

Duplicated IDS : 0

2. Eliminamos posibles duplicados

In [9]:
df_master = df_master.drop_duplicates(subset=["customer_id"])

3. Estandarizacion

In [10]:
cols_texto = [
    "customer_name",
    "customer_segment",
    "customer_city",
    "customer_state",
    "customer_country",
    "region",
]

for col in cols_texto:
    df_master[col] = df_master[col].astype(str).str.strip()

In [11]:
df_master["customer_postal_code"] = df_master["customer_postal_code"].astype(str)

In [12]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  str
 1   customer_name              25000 non-null  str
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  str
 4   customer_segment           25000 non-null  str
 5   customer_city              25000 non-null  str
 6   customer_state             25000 non-null  str
 7   customer_country           25000 non-null  str
 8   region                     25000 non-null  str
 9   customer_postal_code       25000 non-null  str
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(1), str(9)
memory usage: 2.1 MB

In [13]:
os.makedirs("../data/processed", exist_ok=True)
df_master.to_csv("../data/processed/customer_master_clean.csv", index=False)
print("¡Archivo guardado exitosamente!")

¡Archivo guardado exitosamente!

# 2. Product Catalog

In [14]:
df_products = pd.read_csv("../data/raw/product_catalog.csv")

In [15]:
df_products

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9
...,...,...,...,...,...,...,...,...,...
1170,PROD-001171,Avery Inverse 4thgeneration productivity Calen...,Office Supplies,Calendars,Avery,Amazon Supply,107.23,33.97,4.8
1171,PROD-001172,Staples Future-proofed zero tolerance knowledg...,Office Supplies,Calendars,Staples,Pacific Trade,246.92,126.70,4.8
1172,PROD-001173,Mead Pre-emptive discrete help-desk Calendars,Office Supplies,Calendars,Mead,Alibaba,34.68,13.75,2.7
1173,PROD-001174,Avery Reactive homogeneous Internet solution C...,Office Supplies,Calendars,Avery,Asian Manufacturing,71.13,25.42,3.6
1174,PROD-001175,Office Depot Enterprise-wide systemic paradigm...,Office Supplies,Calendars,Office Depot,Amazon Supply,87.88,28.58,2.9

In [16]:
df_products.info()
print("Nulos:\n", df_products.isnull().sum())
print("IDs duplicados:", df_products.duplicated(subset=["product_id"]).sum())

<class 'pandas.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1175 non-null   str
 1   product_name         1175 non-null   str
 2   product_category     1175 non-null   str
 3   product_subcategory  1175 non-null   str
 4   brand                1175 non-null   str
 5   supplier             1175 non-null   str
 6   unit_price           1175 non-null   float64
 7   product_cost         1175 non-null   float64
 8   product_rating       1175 non-null   float64
dtypes: float64(3), str(6)
memory usage: 82.7 KB
Nulos:
 product_id             0
product_name           0
product_category       0
product_subcategory    0
brand                  0
supplier               0
unit_price             0
product_cost           0
product_rating         0
dtype: int64
IDs duplicados: 0

3. Limpieza de datos

In [17]:
cols_str = [
    "product_name",
    "product_category",
    "product_subcategory",
    "brand",
    "supplier",
]

for col in cols_str:
    df_products[col] = df_products[col].astype(str).str.strip()

In [18]:
invalid_prices = df_products[df_products["unit_price"] < df_products["product_cost"]]

In [19]:
print(f"Productos con precio menor al costo: {len(invalid_prices)}")

Productos con precio menor al costo: 0

In [20]:
df_products.to_csv("../data/processed/product_catalog_clean.csv", index=False)

# 3. Order Items

In [21]:
df_orders = pd.read_csv("../data/raw/order_items.csv")

In [22]:
df_orders.head()

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

In [23]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             397569 non-null  str
 1   product_id           397569 non-null  str
 2   quantity             397569 non-null  int64
 3   unit_price           397569 non-null  float64
 4   discount_percentage  397569 non-null  float64
 5   discount_amount      397569 non-null  float64
 6   gross_sales          397569 non-null  float64
 7   tax_amount           397569 non-null  float64
 8   shipping_cost        397569 non-null  float64
 9   net_sales            397569 non-null  float64
 10  product_cost         397569 non-null  float64
 11  profit               397569 non-null  float64
dtypes: float64(9), int64(1), str(2)
memory usage: 36.4 MB

In [24]:
df_orders = (
    df_orders.groupby(["order_id", "product_id"], as_index=False)
    .agg(
        {
            "quantity": "sum",
            "unit_price": "mean",
            "discount_percentage": "mean",
            "discount_amount": "sum",
            "gross_sales": "sum",
            "tax_amount": "sum",
            "shipping_cost": "sum",
            "net_sales": "sum",
            "product_cost": "sum",
            "profit": "sum",
        }
    )
)

In [25]:
cols_moneda = [
    "discount_amount",
    "gross_sales",
    "tax_amount",
    "shipping_cost",
    "net_sales",
    "product_cost",
    "profit",
]

df_orders[cols_moneda] = df_orders[cols_moneda].round(2)

4. Optimizacion de datos (RAM BIG DATA)

In [26]:
df_orders["order_id"] = df_orders["order_id"].astype(str)
df_orders["product_id"] = df_orders["product_id"].astype(str)

In [27]:
df_orders.to_csv("../data/processed/order_items_clean.csv", index=False)

# 4. Ecommerce Sales Analytics

In [28]:
df_sales = pd.read_csv("../data/raw/ecommerce_sales_customer_analytics.csv")

1. Conversion de Horas y Fechas

In [29]:
df_sales["order_datetime"] = pd.to_datetime(df_sales["order_date"] + " " + df_sales["order_time"], errors="coerce")
df_sales["order_date"] = pd.to_datetime(df_sales["order_date"])

2. Tratamiento e imputación explícita de valores nulos

In [30]:
df_sales["return_status"] = df_sales["return_status"].fillna("No Returned")
df_sales["return_reason"] = df_sales["return_reason"].fillna("N/A")
df_sales["campaign_name"] = df_sales["campaign_name"].fillna("Organic / None")
df_sales["coupon_code"] = df_sales["coupon_code"].fillna("No Coupon")
df_sales["customer_review"] = df_sales["customer_review"].fillna("No Review Provided")
df_sales["review_sentiment"] = df_sales["review_sentiment"].fillna("No Review")

3. Normalización de cadenas de texto y código postal

In [31]:
df_sales["customer_postal_code"] = df_sales["customer_postal_code"].astype(str)
cols_str_sales = ["customer_name", "customer_city", "customer_state"]
for col in cols_str_sales:
    df_sales[col] = df_sales[col].astype(str).str.strip()

In [32]:
# Definir tasas de cambio aproximadas o estándar a USD
exchange_rates = {
    'USD': 1.00,
    'EUR': 1.08, 
    'GBP': 1.27,  
    'CAD': 0.74,  
    'AUD': 0.65,  
    'INR': 0.012, # 1 INR = 0.012 USD
    'AED': 0.27   
}

# Crear la columna de tasa de cambio y convertir las ventas netas a USD
df_sales['exchange_rate'] = df_sales['currency'].map(exchange_rates)
df_sales['net_sales_usd'] = (df_sales['net_sales'] / df_sales['exchange_rate']).round(2)
df_sales['profit_usd'] = (df_sales['profit'] / df_sales['exchange_rate']).round(2)

print("¡Conversión a USD realizada con éxito!")
df_sales[['order_id', 'currency', 'net_sales', 'exchange_rate', 'net_sales_usd']].head()

¡Conversión a USD realizada con éxito!

     order_id currency  net_sales  exchange_rate  net_sales_usd
0  ORD-301242      USD     945.40          1.000         945.40
1  ORD-773460      EUR    2018.41          1.080        1868.90
2  ORD-449374      USD     468.35          1.000         468.35
3  ORD-567636      USD     546.52          1.000         546.52
4  ORD-820028      INR    2785.27          0.012      232105.83

In [33]:
# 1. Asegurar limpieza y formato numérico estricto en net_sales y profit
cols_a_limpiar = ['net_sales', 'gross_sales', 'profit', 'tax_amount', 'shipping_cost']

for col in cols_a_limpiar:
    if col in df_sales.columns:
        # Convertir a numérico forzando errores a NaN y luego redondear a 2 decimales exactos
        df_sales[col] = pd.to_numeric(df_sales[col], errors='coerce').round(2)

# 2. Crear la columna en Dólares (USD) ya limpia y redondeada
# (Si ya tienes el diccionario de divisas aplicado)
if 'currency' in df_sales.columns and 'exchange_rate' in df_sales.columns:
    df_sales['net_sales_usd'] = (df_sales['net_sales'] / df_sales['exchange_rate']).round(2)

In [34]:
df_sales

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,order_datetime,exchange_rate,net_sales_usd,profit_usd
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,588.33,345.04,36.50,12459.68,True,11,2023-11-06 16:37:47,1.000,945.40,345.04
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,2031.88,-22.47,-1.11,13032.48,True,11,2025-12-24 01:22:36,1.080,1868.90,-20.81
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,257.73,197.57,42.18,6159.44,True,6,2021-07-05 14:24:21,1.000,468.35,197.57
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,277.84,247.83,45.35,5638.30,True,7,2023-01-21 07:20:26,1.000,546.52,247.83
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,1231.88,1530.36,54.94,13240.10,True,8,2022-05-13 09:46:21,0.012,232105.83,127530.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,101.77,116.50,51.91,18182.63,True,14,2025-09-27 13:00:50,1.000,224.42,116.50
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,1246.73,1004.89,44.45,10004.74,True,10,2023-07-22 09:13:25,1.000,2260.80,1004.89
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,970.95,1263.27,55.87,16442.68,True,15,2025-09-08 18:30:32,1.270,1780.44,994.70
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,1042.40,953.59,45.84,8047.00,True,5,2022-04-06 14:50:07,1.000,2080.38,953.59
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,884.46,678.67,43.17,4107.38,True,5,2022-11-23 11:46:00,1.000,1572.22,678.67

4. Guardar el archivo limpio en la carpeta processed

In [37]:
df_sales.to_csv("../data/processed/ecommerce_sales_analytics_clean.csv", index=False)